In [2]:
# loading pandas module
import pandas as pd
# loading numpy module
import numpy as np
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier

In [7]:
#Object iris contain iris data
iris = load_iris()
#print(iris)
df = pd.DataFrame(iris.data,columns=iris.feature_names)
df.head()


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [11]:
# we dont have the output ie what type of flower is this. For that we need to add a column to our data frame called species.
# below code creates a new column names 'species' in data frame
df['species'] = pd.Categorical.from_codes(iris.target,iris.target_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [52]:
# one more column indicating trained and test data 
# with below code, 75 % of the data is trained and 25% is used to test our accuracy
df['is_train'] = np.random.uniform(0,1,len(df)) <= 0.75
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  is_train  
0  setosa     False  
1  setosa      True  
2  setosa      True  
3  setosa      True  
4  setosa      True

In [53]:
# create 2 different variables 'train' and 'test' with trained rows and test columns

train, test = df[df['is_train']==True], df[df['is_train'] == False]

train.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   
5                5.4               3.9                1.7               0.4   

  species  is_train  
1  setosa      True  
2  setosa      True  
3  setosa      True  
4  setosa      True  
5  setosa      True

In [54]:
test.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
17                5.1               3.5                1.4               0.3   
23                5.1               3.3                1.7               0.5   
25                5.0               3.0                1.6               0.2   
28                5.2               3.4                1.4               0.2   

   species  is_train  
0   setosa     False  
17  setosa     False  
23  setosa     False  
25  setosa     False  
28  setosa     False

In [56]:
# show number of observations in Trained and test data frame

print("Number of observations in train dataset : " ,len(train))
print("Number of observations in test dataset : " ,len(test))

Number of observations in train dataset :  110
Number of observations in test dataset :  40


In [57]:
features = df.columns[:4]
features

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [58]:
# Convert the species into integers that computer can understand.

y = pd.factorize(train['species'])[0]
y

# this gives 3 different species with 3 different integers

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
      dtype=int64)

In [59]:
clf = RandomForestClassifier(n_jobs=2,random_state=0)

In [61]:
# fit method is used for training the data set
clf.fit(train[features],y)
# trained our model

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [62]:
# predict method is used to test our remaining data in dataset

clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 2, 2], dtype=int64)

In [63]:
# below code help to view the probability of each observation
clf.predict_proba(test[features])

array([[1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0.9, 0.1],
       [0. , 1. , 0. ],
       [0. , 0.8, 0.2],
       [0. , 0.9, 0.1],
       [0. , 1. , 0. ],
       [0. , 0.7, 0.3],
       [0. , 0.9, 0.1],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [0. , 0.9, 0.1],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ],
       [0. , 0. , 1. ],
       [0. , 0. , 1. ],
       [0. , 0. , 1. ],
       [0. , 0.9, 0.1],
       [0. , 0. , 1. ],
       [0. , 0.2, 0.8],
       [0. , 0. , 1. ],
       [0. , 0.5, 0.5],
       [0. , 0. , 1. ],
       [0. , 0.8, 0.2],
       [0. , 0. , 1. ],
       [0. , 0. , 1. ],
       [0. , 0.7, 0.3],
       [0. , 0. , 1. ],
       [0. , 0. , 1. ],
       [0. , 0. , 1. ]])

In [66]:
# mapping plant names to test features 0 - setosa , 1 - versicolor 2 - virginica 
preds=iris.target_names[clf.predict(test[features])]
preds[10:25]

array(['versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'virginica',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'virginica', 'virginica'], dtype='<U10')

In [70]:
# creating confusion matrix
pd.crosstab(test['species'],preds,rownames=['Actual Species'],colnames=['Predicted species'])

Predicted species  setosa  versicolor  virginica
Actual Species                                  
setosa                 10           0          0
versicolor              0          12          1
virginica               0           4         13

In [ ]:
# from the confusion matrix, Total number of accurate predictions = 10+12+13 = 35
# Total number of inaccurate predictions = 5
# therefore Model accuracy = 35/40 * 100 = 87.5